export const objectTypesSeed = [
  ['lamp', 'Lamp'],
  ['chandelier', 'Chandelier'],
  ['jewelry', 'Jewelry'],
  ['taxidermy', 'Taxidermy'],
  ['skull', 'Skull'],
  ['crystal', 'Crystal'],
  ['fossil', 'Fossil'],
  ['specimen', 'Specimen'],
  ['artwork', 'Artwork'],
  ['print', 'Print'],
  ['book', 'Book'],
  ['media', 'Media'],
  ['decor', 'Decor'],
  ['furniture', 'Furniture'],
  ['oddity', 'Oddity'],
  ['ritual-object', 'Ritual Object'],
  ['collectible', 'Collectible'],
  ['garment', 'Garment'],
  ['shirt', 'Shirt'],
  ['accessory', 'Accessory'],
  ['mask', 'Mask'],
  ['signage', 'Signage'],
  ['arcade', 'Arcade'],
  ['archive-item', 'Archive Item'],
  ['tool', 'Tool'],
  ['supplies', 'Supplies'],
] as const;

export const locationsSeed = [
  ['compound', 'Compound', 'compound', null],
  ['tiger-dust-store', 'Tiger Dust Store', 'storefront', null],
  ['archive-storage', 'Archive Storage', 'archive', null],
  ['liquidation-holding', 'Liquidation Holding', 'liquidation', null],
  ['guest-house-staging', 'Guest House Staging', 'staging', 'compound'],
  ['lamp-lab', 'Lamp Lab', 'studio', 'compound'],
  ['jewelry-studio', 'Jewelry Studio', 'studio', 'compound'],
  ['photo-station', 'Photo Station', 'studio', 'compound'],
  ['screen-printing', 'Screen Printing Area', 'studio', 'compound'],
  ['intake-holding', 'Intake Holding', 'storage', 'compound'],
  ['store-sales-floor', 'Sales Floor', 'storefront', 'tiger-dust-store'],
  ['store-front-window', 'Front Window Display', 'storefront', 'tiger-dust-store'],
  ['store-back-room', 'Back Room', 'storage', 'tiger-dust-store'],
  ['store-counter-display', 'Counter Display', 'storefront', 'tiger-dust-store'],
  ['repair-hold', 'Repair Hold', 'storage', 'compound'],
  ['research-hold', 'Research Hold', 'storage', 'compound'],
  ['photo-ready-hold', 'Photo Ready Hold', 'staging', 'compound'],
  ['priced-ready-hold', 'Priced Ready Hold', 'staging', 'compound'],
] as const;

export const starterTagsSeed = [
  ['occult', 'Occult', 'theme'],
  ['gothic', 'Gothic', 'style'],
  ['victorian', 'Victorian', 'era'],
  ['macabre', 'Macabre', 'theme'],
  ['playful', 'Playful', 'theme'],
  ['mystical', 'Mystical', 'theme'],
  ['handmade', 'Handmade', 'process'],
  ['one-of-a-kind', 'One of a Kind', 'theme'],
  ['brass', 'Brass', 'material'],
  ['silver', 'Silver', 'material'],
  ['bone', 'Bone', 'material'],
  ['wood', 'Wood', 'material'],
  ['glass', 'Glass', 'material'],
  ['crystal', 'Crystal', 'material'],
  ['stone', 'Stone', 'material'],
  ['velvet', 'Velvet', 'material'],
  ['skull', 'Skull', 'motif'],
  ['snake', 'Snake', 'motif'],
  ['moon', 'Moon', 'motif'],
  ['star', 'Star', 'motif'],
  ['fossil', 'Fossil', 'motif'],
  ['restored', 'Restored', 'process'],
  ['repaired', 'Repaired', 'process'],
  ['photographed', 'Photographed', 'process'],
  ['researched', 'Researched', 'process'],
  ['handmade-by-laura', 'Handmade by Laura', 'process'],
  ['lapidary', 'Lapidary', 'process'],
] as const;

export const collectionsSeed = [
  ['featured-now', 'Featured Now', 'public'],
  ['wonder-room', 'Wonder Room', 'public'],
  ['taxidermy-and-skulls', 'Taxidermy & Skulls', 'public'],
  ['occult-books-and-media', 'Occult Books & Media', 'public'],
  ['crystals-and-fossils', 'Crystals & Fossils', 'public'],
  ['lamps-and-glow', 'Lamps & Glow', 'public'],
  ['jewelry-and-handmade', 'Jewelry & Handmade', 'public'],
  ['archived-favorites', 'Archived Favorites', 'internal'],
] as const;

export const workflowEventTypesSeed = [
  'intake_created',
  'intake_updated',
  'location_moved',
  'cleaning_started',
  'cleaning_completed',
  'repair_started',
  'repair_completed',
  'lapidary_started',
  'lapidary_completed',
  'fabrication_started',
  'fabrication_completed',
  'photography_started',
  'photography_completed',
  'research_started',
  'research_added',
  'pricing_set',
  'route_changed',
  'publish_enabled',
  'publish_disabled',
  'sold_recorded',
  'archived_recorded',
] as const;
