export const planningSourceDocs = [
  'TIGER_DUST_V2_SPEC.md',
  'TIGER_DUST_SCHEMA_DRAFT.md',
  'TIGER_DUST_SEED_DATA_DRAFT.md',
  'TIGER_DUST_SCREEN_TO_TABLE_MAPPING.md',
  'TIGER_DUST_MVP_BUILD_CHECKLIST.md',
  'TIGER_DUST_ISSUE_BACKLOG_AND_MILESTONES.md',
] as const;
